services:
  runner:
    image: ccmagruder/runner:latest
    build:
      dockerfile: Dockerfile
      context: .runner
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - REPO=ccmagruder/gemm
    secrets:
      - token

secrets:
  token:
    file: ./.gh_pat
