services:
  devcontainer:
    image: ccmagruder/devcontainer-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .devcontainer
    volumes:
      - type: bind
        source: .
        target: /root/gemm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ide:
    image: ccmagruder/ide-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .ide
    command: zsh
    environment:
      - TERM=xterm-256color
    volumes:
      - type: bind
        source: .
        target: /root/gemm
      - type: bind
        source: ~/.config/nvim
        target: /root/.config/nvim
      - type: bind
        source: ~/.tmux.conf
        target: /root/.tmux.conf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  runner:
    image: ccmagruder/runner-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .runner
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - REPO=ccmagruder/gemm
    secrets:
      - token

secrets:
  token:
    file: ./.gh_pat
