services:
  devcontainer:
    image: ccmagruder/devcontainer-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .devcontainer
    volumes:
      - type: bind
        source: .
        target: /root/gemm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ide:
    image: ccmagruder/ide-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .ide
    command: zsh
    environment:
      - TERM=xterm-256color
      - TZ=America/Chicago
    tty: true
    volumes:
      - type: bind
        source: .
        target: /root/gemm
      - type: bind
        source: ~/.config/nvim
        target: /root/.config/nvim
      - type: bind
        source: ~/.tmux.conf
        target: /root/.tmux.conf
        read_only: true
      - type: bind
        source: ~/.gitconfig
        target: /root/.gitconfig
        read_only: true
      - type: bind
        source: ~/.git-credentials
        target: /root/.git-credentials
        read_only: true
      - type: bind
        source: ./.private.key
        target: /root/.private.key
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jupyter:
    image: ccmagruder/jupyter-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .jupyter
    ports:
      - 8888:8888
    command: bash -c "cd /root/gemm && jupyter lab --allow-root --ip 0.0.0.0"
    volumes:
      - type: bind
        source: .
        target: /root/gemm

  runner:
    image: ccmagruder/runner-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .runner
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - REPO=ccmagruder/gemm
    runtime: sysbox-runc
    secrets:
      - token
    volumes:
      - docker-cache:/var/lib/docker

secrets:
  token:
    file: ./.gh_pat

volumes:
  docker-cache:
