services:
  devcontainer:
    image: ccmagruder/devcontainer-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .devcontainer
    volumes:
      - type: bind
        source: ./gemm
        target: /root/gemm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  runner:
    image: ccmagruder/runner-gemm:latest
    build:
      dockerfile: Dockerfile
      context: .runner
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - REPO=ccmagruder/gemm
    secrets:
      - token

secrets:
  token:
    file: ./.gh_pat
