name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  devcontainer:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: docker build
        run: docker compose build devcontainer

      - name: nvidia-smi
        run: docker compose run --rm devcontainer nvidia-smi

  build:
    needs: devcontainer
    runs-on: self-hosted
    container:
      image: ccmagruder/devcontainer-gemm
      options: --gpus all
    steps:
      - name: nvidia-smi
        run: nvidia-smi

      - name: checkout repo
        uses: actions/checkout@v4

      - name: cmake configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -S gemm -B build .

      - name: cmake build
        run: cmake --build build

      - name: google test
        run: ctest --test-dir build --output-on-failure

      - name: google benchmark
        run: |
          build/tests/bMatrix
          build/tests/bGemm
