name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: [self-hosted, linux, x86]
    steps:
      - name: Say Hello
        run: echo "Hello, World!"


